parameters:
    projectstack.con: "tests"
    projectstack.template_engine_class: Webforge\View\Mustache\Mustache

services:
    projectstack.boot_container_service:
      class: Webforge\ProjectStack\BootContainerService

    projectstack.boot_container:
      class: Webforge\ProjectStack\BootContainer
      factory_service: projectstack.boot_container_service
      factory_method: getBootContainer

    projectstack.kernel:
      class: Webforge\ProjectStack\Symfony
      factory_service: projectstack.boot_container
      factory_method: getKernel

    projectstack.webforge:
      class: Webforge\Framework\Container
      factory_service: projectstack.boot_container
      factory_method: getWebforge

    projectstack.project:
      class: Webforge\Framework\Project
      factory_service:  projectstack.boot_container
      factory_method:   getProject


    projectstack.directory_tpl:
      class: Webforge\Common\System\Dir
      factory_service: projectstack.project
      factory_method: dir
      arguments: ["tpl"]

    projectstack.directory_tpl_cache:
      class: Webforge\Common\System\Dir
      factory_service: projectstack.project
      factory_method: dir
      arguments: ["tpl-cache"]

    projectstack.template_engine:
      class: %projectstack.template_engine_class%
      arguments:
        - @projectstack.directory_tpl
        - @projectstack.directory_tpl_cache

    # general definition for a symfony templating engine
    templating.engine.mustache:
      class: Webforge\View\SymfonyAdapter
      arguments: 
        - @projectstack.template_engine
        - @templating.name_parser
        - @templating.loader
        - @router

    projectstack.dcc:
      class: Webforge\Doctrine\Container
      factory_service: projectstack.boot_container
      factory_method:  getDoctrineContainer

    projectstack.entity_manager:
      class: Doctrine\ORM\EntityManager
      factory_service:  projectstack.dcc
      factory_method:  getEntityManager
      arguments:
        - "%projectstack.con%"

    projectstack.systemcontainer:
      class: Webforge\Common\System\System
      factory_service:  projectstack.webforge
      factory_method:  getSystemContainer

    projectstack.system:
      class: Webforge\Common\System\System
      factory_service:  projectstack.systemcontainer
      factory_method:  getSystem

    projectstack.doctrine.compile_command:
      class: Webforge\Doctrine\Compiler\Console\CompileCommand
      arguments:
        - @projectstack.dcc
        - @projectstack.system

    projectstack.cli.application:
      class:     Symfony\Bundle\FrameworkBundle\Console\Application
      arguments: ['@projectstack.kernel']

    # deprecated. try to use the jms serializer not this builder and the projectstack.serializer
    projectstack.serializer_builder:
      class:     Webforge\Serializer\SerializerBuilder

    # deprecated. try to use the jms serializer not this builder and the projectstack.serializer
    projectstack.serializer:
      class:     JMS\Serializer\Serializer
      factory_service: projectstack.serializer_builder
      factory_method: getSerializer

    # hook the WebforgeDateTime handler into jms serializer (NOT into our serializer build with SerializerBuilder)
    projectstack.serializer.datetimehandler:
      class:      Webforge\Serializer\DateTimeHandler
      tags: 
        - { name: jms_serializer.subscribing_handler }

    # cli
    projectstack.command.rundql:
      class:     Webforge\ProjectStack\Symfony\Console\RunDqlCommand
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
        -  { name: console.command }

    projectstack.command.:
      class:     Webforge\ProjectStack\Symfony\Console\CompileModelCommand
      arguments: ["@projectstack.system"]
      tags:
        -  { name: console.command }

    projectstack.views.factory:
      class:     Webforge\ProjectStack\View\Factory
      arguments: ["@projectstack.project", "@doctrine.orm.entity_manager", "@router", "@markdown.parser"]
