parameters:
    projectstack.con: "tests"
    projectstack.template_engine_class: Webforge\View\Mustache\Mustache

services:
    projectstack.boot_container_service:
      class: Webforge\ProjectStack\BootContainerService

    projectstack.boot_container:
      class: Webforge\Setup\BootContainer
      factory_service: projectstack.boot_container_service
      factory_method: getBootContainer

    projectstack.webforge:
      class: Webforge\Framework\Container
      factory_service: projectstack.boot_container
      factory_method: getWebforge

    projectstack.project:
      class: Webforge\Framework\Project
      factory_service:  projectstack.boot_container
      factory_method:   getProject

    projectstack.container:
      class: Webforge\ProjectStack\Container
      arguments:
        - @projectstack.project

    projectstack.directory_tpl:
      class: Webforge\Common\System\Dir
      factory_service: projectstack.project
      factory_method: dir
      arguments: ["tpl"]

    projectstack.directory_tpl_cache:
      class: Webforge\Common\System\Dir
      factory_service: projectstack.project
      factory_method: dir
      arguments: ["tpl-cache"]

    projectstack.template_engine:
      class: %projectstack.template_engine_class%
      arguments:
        - @projectstack.directory_tpl
        - @projectstack.directory_tpl_cache

    # general definition for a symfony templating engine
    templating.engine.mustache:
      class: Webforge\View\SymfonyAdapter
      arguments: 
        - @projectstack.template_engine
        - @templating.name_parser
        - @templating.loader
        - @router

    projectstack.dcc:
      class: Webforge\Doctrine\Container
      factory_service: projectstack.container
      factory_method:  getDoctrineContainer

    projectstack.entity_manager:
      class: Doctrine\ORM\EntityManager
      factory_service:  projectstack.dcc
      factory_method:  getEntityManager
      arguments:
        - "%projectstack.con%"

    projectstack.systemcontainer:
      class: Webforge\Common\System\System
      factory_service:  projectstack.webforge
      factory_method:  getSystemContainer

    projectstack.system:
      class: Webforge\Common\System\System
      factory_service:  projectstack.systemcontainer
      factory_method:  getSystem

    projectstack.doctrine.compile_command:
      class: Webforge\Doctrine\Compiler\Console\CompileCommand
      arguments:
        - @projectstack.dcc
        - @projectstack.system
